In [1]:
import tensorflow as tf
import numpy as np
import cv2
import time

<h3>Tensor Flow Related Testing</h3>

In [2]:
# Load TFLite model and allocate tensors. #Downloaded model from:
interpreter = tf.lite.Interpreter(model_path="posenet_mobilenet_v1_100_257x257_multi_kpt_stripped.tflite")
interpreter.allocate_tensors()

In [3]:
# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

In [4]:
input_details

[{'name': 'sub_2',
  'index': 93,
  'shape': array([  1, 257, 257,   3], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0)}]

In [5]:
output_details

[{'name': 'MobilenetV1/heatmap_2/BiasAdd',
  'index': 87,
  'shape': array([ 1,  9,  9, 17], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0)},
 {'name': 'MobilenetV1/offset_2/BiasAdd',
  'index': 90,
  'shape': array([ 1,  9,  9, 34], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0)},
 {'name': 'MobilenetV1/displacement_fwd_2/BiasAdd',
  'index': 84,
  'shape': array([ 1,  9,  9, 32], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0)},
 {'name': 'MobilenetV1/displacement_bwd_2/BiasAdd',
  'index': 81,
  'shape': array([ 1,  9,  9, 32], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0)}]

In [6]:
# Test model on random input data.
input_shape = input_details[0]['shape']

input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)

interpreter.set_tensor(input_details[0]['index'], input_data)

In [7]:
interpreter.invoke()

In [8]:
# The function `get_tensor()` returns a copy of the tensor data.
# Use `tensor()` in order to get a pointer to the tensor.
output_data = interpreter.get_tensor(output_details[0]['index'])

In [9]:
output_data

array([[[[-10.5235195, -10.971067 , -10.676756 , ..., -10.748573 ,
          -11.41351  , -11.165659 ],
         [ -9.290961 ,  -9.0730095,  -9.762179 , ...,  -9.613972 ,
           -9.765279 ,  -9.42326  ],
         [ -9.078714 ,  -8.817985 ,  -9.741149 , ...,  -9.400692 ,
           -8.908912 ,  -8.90143  ],
         ...,
         [ -8.737001 ,  -7.694943 ,  -9.433006 , ...,  -9.699088 ,
           -9.142742 ,  -8.4742565],
         [ -8.850085 ,  -7.471795 ,  -9.240179 , ..., -10.570064 ,
          -10.192246 , -11.083973 ],
         [ -7.3409214,  -6.4745297,  -7.4059434, ...,  -9.117925 ,
           -8.382356 ,  -7.5295706]],

        [[-10.5779   , -10.550861 , -11.139762 , ..., -12.424705 ,
          -12.847317 , -12.713907 ],
         [ -9.421811 ,  -9.568249 ,  -9.531855 , ...,  -9.790011 ,
          -11.217549 , -10.483366 ],
         [-11.659521 , -12.017034 , -11.538467 , ...,  -9.370039 ,
          -10.963412 , -10.371504 ],
         ...,
         [-11.6797695, -11.066576 

<h3>OpenCV related Testing:</h3>

In [13]:
testing = []
def show_webcam(mirror=False):
    cam = cv2.VideoCapture(0)
    while True: 
        ret_val, img = cam.read()
        if mirror: 
            img = cv2.flip(img, 1)
#         img = img.astype(np.float32)
#         img = img / 255
#         img = np.array(img, dtype=np.float32)
#         interpreter.set_tensor(input_details[0]['index'], img)
        
#         interpreter.invoke()
        
#         output_data = interpreter.get_tensor(output_details[0]['index'])
#         output_img = outputdata.astype(np.uint8)
        testing.append(img)#Appends every image frame captured for the time. 
#         img = img.astype(np.int8)
        cv2.imshow('my webcam', img)
        if cv2.waitKey(1) == 27: 
            break  # esc to quit
    cv2.destroyAllWindows()

<p>Activates Camera:</p>

In [14]:
show_webcam(mirror=True)

error: OpenCV(4.1.1) /Users/travis/build/skvark/opencv-python/opencv/modules/highgui/src/window.cpp:352: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'imshow'


In [19]:
testing[253]

array([[[ 32,  32,  41],
        [ 27,  27,  36],
        [ 14,  24,  39],
        ...,
        [ 14,  31,  68],
        [ 11,  24,  68],
        [  7,  19,  64]],

       [[ 29,  30,  39],
        [ 21,  21,  30],
        [  9,  20,  35],
        ...,
        [ 12,  28,  65],
        [ 11,  24,  68],
        [ 10,  23,  67]],

       [[ 18,  17,  31],
        [ 19,  18,  32],
        [  6,  15,  35],
        ...,
        [ 18,  27,  69],
        [ 18,  23,  68],
        [ 16,  21,  66]],

       ...,

       [[145, 138,  89],
        [143, 136,  86],
        [144, 139,  90],
        ...,
        [129, 123,  91],
        [128, 122,  88],
        [126, 120,  86]],

       [[134, 130,  76],
        [141, 137,  83],
        [138, 139,  84],
        ...,
        [119, 120,  88],
        [117, 119,  82],
        [125, 127,  90]],

       [[138, 135,  80],
        [139, 136,  82],
        [128, 129,  75],
        ...,
        [123, 123,  91],
        [123, 124,  88],
        [120, 122,  85]]

<h3>Test Webcam Outputdata</h3>

In [ ]:
# Test model on random input data.
input_shape = input_details[0]['shape']

input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)

interpreter.set_tensor(input_details[0]['index'], input_data)

In [20]:
lets_see = testing[253]/255
lets_see

array([[[0.1254902 , 0.1254902 , 0.16078431],
        [0.10588235, 0.10588235, 0.14117647],
        [0.05490196, 0.09411765, 0.15294118],
        ...,
        [0.05490196, 0.12156863, 0.26666667],
        [0.04313725, 0.09411765, 0.26666667],
        [0.02745098, 0.0745098 , 0.25098039]],

       [[0.11372549, 0.11764706, 0.15294118],
        [0.08235294, 0.08235294, 0.11764706],
        [0.03529412, 0.07843137, 0.1372549 ],
        ...,
        [0.04705882, 0.10980392, 0.25490196],
        [0.04313725, 0.09411765, 0.26666667],
        [0.03921569, 0.09019608, 0.2627451 ]],

       [[0.07058824, 0.06666667, 0.12156863],
        [0.0745098 , 0.07058824, 0.1254902 ],
        [0.02352941, 0.05882353, 0.1372549 ],
        ...,
        [0.07058824, 0.10588235, 0.27058824],
        [0.07058824, 0.09019608, 0.26666667],
        [0.0627451 , 0.08235294, 0.25882353]],

       ...,

       [[0.56862745, 0.54117647, 0.34901961],
        [0.56078431, 0.53333333, 0.3372549 ],
        [0.56470588, 0

In [ ]:
interpreter.invoke()

In [ ]:
# The function `get_tensor()` returns a copy of the tensor data.
# Use `tensor()` in order to get a pointer to the tensor.
output_data = interpreter.get_tensor(output_details[0]['index'])

<h3>Checking Data Types:</h3>

<p>The input for tensorflow model:</p>

In [44]:
input_data[0]

array([[[0.60171694, 0.48094502, 0.570192  ],
        [0.4972064 , 0.4504703 , 0.73241085],
        [0.8099531 , 0.689703  , 0.88571006],
        ...,
        [0.96492064, 0.63101375, 0.78173435],
        [0.00728458, 0.4717146 , 0.7706504 ],
        [0.285797  , 0.41046557, 0.7927695 ]],

       [[0.65914404, 0.07503732, 0.5406393 ],
        [0.80581164, 0.02606768, 0.9773528 ],
        [0.3284326 , 0.5071868 , 0.72417456],
        ...,
        [0.44269714, 0.03603778, 0.51720876],
        [0.44086447, 0.29159352, 0.30140233],
        [0.57323647, 0.689344  , 0.6729426 ]],

       [[0.64367825, 0.31391305, 0.71673703],
        [0.5694511 , 0.8536724 , 0.7120923 ],
        [0.7577681 , 0.40115514, 0.07102668],
        ...,
        [0.47418043, 0.36499605, 0.13822328],
        [0.5004392 , 0.7963763 , 0.77291083],
        [0.1384533 , 0.77036893, 0.15186547]],

       ...,

       [[0.2329347 , 0.8575807 , 0.35385698],
        [0.06138156, 0.8956737 , 0.12093463],
        [0.7311093 , 0

<p>Output from OpenCV camera data:</p>

In [26]:
see = testing[0][0].astype(np.float32)

In [27]:
see

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       ...,
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

<h3>Need to Convert unit8 to float32

In [44]:
# cam = cv2.VideoCapture(0)
# ret_val, img = cam.read()
# cv2.imshow('my webcam', img)
# cv2.waitKey(0)
# cv2.destroyAllWindows()